### ISSUE TITLE
Multiple reload

### ISSUE THREAD

**Issue by jbialobr** [bergerjac/gitextensions#15]
If you put a breakpoint you will see that reload is called two times at startup.

I think it would be better to react on GitUICommandsChanged event. Like it was in my branch.

```
    void UICommandsSource_GitUICommandsChanged(IGitUICommandsSource sender, GitUICommands oldCommands)
    {
        RepoChanged();
    }
```

**Comment by bergerjac** [comment]
I think I've remedied this issue [here](https://github.com/bergerjac/gitextensions/commit/3991a3610791b475eb5ec11ebc763257ff3425c1#L3R46).

**Comment by jbialobr** [comment]
UICommandsSource can be assigned no more that once, so https://github.com/bergerjac/gitextensions/commit/3991a3610791b475eb5ec11ebc763257ff3425c1#L0L1801 should be enough.
