### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by jbialobr** [bergerjac/gitextensions#19]
System.NullReferenceException was unhandled by user code
  Message=Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
  Source=GitUI
  StackTrace:
       w GitUI.UserControls.RepoObjectsTree.Node.GetNode(TreeNode treeNode) w D:\projekty\GitExtensionsDev\GitUI\RepoObjectsTree\ROT.Nodes.cs:wiersz 86
       w GitUI.UserControls.RepoObjectsTree.OnTreeDragOver(Object sender, DragEventArgs e) w D:\projekty\GitExtensionsDev\GitUI\RepoObjectsTree\ROT.DragDrops.cs:wiersz 92
       w System.Windows.Forms.Control.OnDragOver(DragEventArgs drgevent)
       w System.Windows.Forms.Control.System.Windows.Forms.IDropTarget.OnDragOver(DragEventArgs drgEvent)
       w System.Windows.Forms.DropTarget.System.Windows.Forms.UnsafeNativeMethods.IOleDropTarget.OleDragOver(Int32 grfKeyState, Int64 pt, Int32& pdwEffect)
  InnerException:

**Comment by bergerjac** [comment]
What were you hovering over? I think it may be because `TreeNode.Tag` property [was not being set](https://github.com/bergerjac/gitextensions/commit/f4fd0#L3R26).

Please test this [new push](https://github.com/bergerjac/gitextensions/tree/f4fd08).

**Comment by jbialobr** [comment]
It still occurs. To reproduce it you have to drag current branch node and move it down below the tree.
